### ISSUE TITLE
Scoreboard cannot be null

### ISSUE THREAD

**Issue by Jl5her** [Jl5her/MinecraftPlugin#1]
In order to not show a scoreboard to a user, the plugin currently sets their scoreboard as null. The server does not like this implementation.

```
05.04 02:53:26 [Server] WARN Task #17 for Core v1.3.1 generated an exception
05.04 02:53:26 [Server] INFO java.lang.IllegalArgumentException: Scoreboard cannot be null
05.04 02:53:26 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.setScoreboard(CraftPlayer.java:1687) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at net.micrlink.core.manager.ScoreboardManager$1.run(ScoreboardManager.java:32) ~[?:?]
05.04 02:53:26 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-161]
05.04 02:53:26 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Jl5her** [comment]
29f82fd027bc48dede87b39e2ecf5ddc8321d327 Resolves this issue
